# Generated by Django 4.0.4 on 2022-05-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userMgt', '0002_profile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('prefered_name', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('salary', models.IntegerField()),
                ('hired_date', models.DateField()),
                ('department', models.CharField(max_length=45)),
            ],
        ),
    ]
